vich_uploader:
    db_driver: orm

    mappings:
        posts:
            uri_prefix: /images/posts
            upload_destination: '%kernel.project_dir%/assets/images/posts'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        users:
            uri_prefix: /images/avatar
            upload_destination: '%kernel.project_dir%/assets/images/avatar'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
